// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBearpNiKl9f-mhUxfvrOQLOTKx_Fbv5sY',
    appId: '1:1067948471437:android:a6649bdd5a416a4b739ec4',
    messagingSenderId: '1067948471437',
    projectId: 'linkping-4b337',
    storageBucket: 'linkping-4b337.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsiiCrft8rP5rjo-_kUvKSLRm9ZFEV4hc',
    appId: '1:1067948471437:ios:657f3fc807befced739ec4',
    messagingSenderId: '1067948471437',
    projectId: 'linkping-4b337',
    storageBucket: 'linkping-4b337.firebasestorage.app',
    androidClientId: '1067948471437-3b9tgj2081kd204lsmkkis81qralm586.apps.googleusercontent.com',
    iosClientId: '1067948471437-e3lqis1p7uvl6k7pk5nr4cke02lk8u5v.apps.googleusercontent.com',
    iosBundleId: 'com.example.linkping',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeWqnF4heZig0AAJLjHsvvfm4S1lskFUs',
    appId: '1:1067948471437:web:c46e5183a3d7d027739ec4',
    messagingSenderId: '1067948471437',
    projectId: 'linkping-4b337',
    authDomain: 'linkping-4b337.firebaseapp.com',
    storageBucket: 'linkping-4b337.firebasestorage.app',
    measurementId: 'G-5X28NVEQDM',
  );

}