// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZjoafmdRBbZzGN20SsO497LpIo2fReAs',
    appId: '1:458642757197:android:2a482bf2929e32b94cee04',
    messagingSenderId: '458642757197',
    projectId: 'linkping-prod',
    storageBucket: 'linkping-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHpkeaoABvWCdmzTnFV9vXg-zpYAR43pg',
    appId: '1:458642757197:ios:82a331feff67c3ef4cee04',
    messagingSenderId: '458642757197',
    projectId: 'linkping-prod',
    storageBucket: 'linkping-prod.firebasestorage.app',
    iosBundleId: 'com.drevv.linkping',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm9aV-oKENVzFEXeSKcQi2lQzvXWaoEsg',
    appId: '1:458642757197:web:509ef2cd901a99024cee04',
    messagingSenderId: '458642757197',
    projectId: 'linkping-prod',
    authDomain: 'linkping-prod.firebaseapp.com',
    storageBucket: 'linkping-prod.firebasestorage.app',
    measurementId: 'G-H7JRY2LV9F',
  );
}
